# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy remaining source
COPY . .

# Build the TypeScript project
RUN npm run build

# Set default environment variables (can be overridden at runtime)
ENV SLACK_BOT_TOKEN=dummy_token
ENV SLACK_TEAM_ID=dummy_team_id

# Start the MCP server
CMD ["node", "build/index.js"]

# FROM node:22.12-alpine AS builder

# # Must be entire project because `prepare` script is run during `npm install` and requires all files.
# COPY src/slack /app
# COPY tsconfig.json /tsconfig.json

# WORKDIR /app

# RUN --mount=type=cache,target=/root/.npm npm install

# RUN --mount=type=cache,target=/root/.npm-production npm ci --ignore-scripts --omit-dev

# FROM node:22-alpine AS release

# COPY --from=builder /app/dist /app/dist
# COPY --from=builder /app/package.json /app/package.json
# COPY --from=builder /app/package-lock.json /app/package-lock.json

# ENV NODE_ENV=production

# WORKDIR /app

# RUN npm ci --ignore-scripts --omit-dev

# ENTRYPOINT ["node", "dist/index.js"]
