# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy remaining source
COPY . .

# Build the TypeScript project
RUN npm run build

# Make the output executable for MCP Inspector/Smithery
RUN chmod +x build/index.js

# Set default environment variables (can be overridden at runtime)
ENV SLACK_BOT_TOKEN=dummy_token
ENV SLACK_TEAM_ID=dummy_team_id

# Start the MCP server
CMD ["node", "build/index.js"]

