# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy remaining source
COPY . .

# Build the project
RUN npx tsc

# Expose port if necessary (but it's stdio so none required)

# Set environment variable if needed, but otherwise allow override
# Default to dummy token
ENV SLACK_BOT_TOKEN=dummy_token
ENV SLACK_TEAM_ID=dummy_team_id

# Start the MCP server
CMD [ "node", "build/index.js" ]